language: python
python:
  - "3.5"
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - ./bin/install_solc.sh
  - travis_retry sudo apt-get install -y ethereum
  - mkdir -p $HOME/.ethash
  - geth makedag 0 $HOME/.ethash
env:
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=flake8
  global:
    - CHAIN_SYNC_BLOCK_DELTA=100
    - SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/solc/solc"
cache:
  - pip: true
  - directories:
    - solc/solc-0.3.6
    - solc/solidity-0.3.6/build
    - $HOME/.ethash
    - .tox/py27/.hypothesis
    - .tox/py34/.hypothesis
    - .tox/py35/.hypothesis
install:
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
